name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies in CI mode
        run: pnpm ci

      - name: Build
        run: pnpm build

      - name: Configure npm auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat <<'EOF' > ~/.npmrc
          @ulfsoft:registry=https://registry.npmjs.org/
          //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          provenance=true
          EOF

      - name: Publish package
        env:
          GIT_REF: ${{ github.ref }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public --no-git-checks --tag ${GIT_REF}
